# Generated by Django 3.2.19 on 2023-06-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('periodo_de_ingresso', models.CharField(max_length=10, verbose_name='Período de Ingresso')),
                ('nota', models.FloatField(verbose_name='Nota - Web Avançado')),
            ],
        ),
    ]
